src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Comment;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Tricks::class, orphanRemoval: true)]
    private Collection $tricks;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->tricks = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {

    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Tricks>
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Tricks $trick): static
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks->add($trick);
            $trick->setUser($this);
        }

        return $this;
    }

    public function removeTrick(Tricks $trick): static
    {
        if ($this->tricks->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getUser() === $this) {
                $trick->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/TricksController.php
<?php

namespace App\Controller;

use App\Entity\Tricks;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Entity\TricksVideo;
use App\Form\TricksFormType;
use App\Repository\CommentRepository;
use App\Repository\TricksRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\TricksImageRepository;
use DateTimeImmutable;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;


class TricksController extends AbstractController
{
    #[Route('/', name: 'app_home', methods:['GET'])]
    public function index(TricksRepository $tricksRepository,Request $request): Response
    {   
        /** @var \App\Entity\User | null $user */
        $user = $this->getUser();

        if ($user && !$user->isVerified()) {
            $this->addFlash('unverified', "Veuillez vérifiez votre adresse mail");
        }

        $page = max(1, $request->query->getInt('page', 1));
        $paginator = $tricksRepository->getTricksPaginator($page);

        return $this->render('tricks/index.html.twig', [
            'tricks' => $paginator,
            'previous' => $page - 1,
            'next' => min(count($paginator), $page + 1),
            'tricks_per_page' => $tricksRepository::PAGINATOR_PER_PAGE
        ]);
    }

    #[Route('/tricks/{id}', name: 'app_tricks_readOne', methods:['GET','POST'])]
    public function getOne(Tricks $trick, int $id,Request $request,EntityManagerInterface $entityManager,CommentRepository $commentRepository): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        
        if(!$trick)
        {
            $this->addFlash('error',"Ce tricks n'existe pas");
            return $this->redirectToRoute('app_home');
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setUser($this->getUser());
            $comment->setTrick($trick);
            $comment->setDate(new DateTimeImmutable());
            $entityManager->persist($comment);
            $entityManager->flush();

            $this->addFlash('success','Commentaire ajouté');
            return $this->redirectToRoute('app_tricks_readOne',['id' => $trick->getId()]);
        }

        $page = max(1, $request->query->getInt('page', 1));
        $paginator = $commentRepository->getCommentPaginator($trick, $page);

        return $this->render('tricks/readOne.html.twig', [
            'trick' => $trick,
            'form'=> $form,
            'comments' => $paginator,
            'next' => min(count($paginator), $page + 1),
            'comment_per_page' => $commentRepository::PAGINATOR_PER_PAGE,
            'singleTrickPage' => true
        ]);
    }

    #[Route('/ajoutTricks', name: 'app_add_tricks', methods:['GET','POST'])]
    public function add(Request $request, EntityManagerInterface $entityManager): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        if (!$user || !$user->isVerified()) {
            $this->addFlash('error', 'Vous devez posséder un compte et être vérifié pour cela');
            return $this->redirectToRoute('app_home');
        }

        $tricks = new Tricks();

        $form = $this->createForm(TricksFormType::class, $tricks);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tricks->setUser($this->getUser());
            if(!$tricks->getUpdatedAt()){
                $tricks->setUpdatedAt(new DateTimeImmutable());
            }
            $entityManager->persist($tricks);
            $entityManager->flush();

            $this->addFlash('success', 'Tricks ajouté!');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('tricks/form.html.twig', [
            'form' => $form->createView(),
            'tricks' => $tricks,
            'singleTrickPage' => true
        ]);
    }

    #[Route('/editTricks/{id}', name: 'app_edit_tricks', methods:['POST','PUT','GET'])]
    public function edit(Tricks $tricks, Request $request, EntityManagerInterface $entityManager,TricksImageRepository $tricksImageRepository): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        if (!$user || !$user->isVerified()) {
            $this->addFlash('error', 'Vous devez posséder un compte et être vérifié pour cela');
            return $this->redirectToRoute('app_home');
        }

        if ($tricks->getUser() !== $this->getUser()) {
            $this->addFlash('error', 'Le tricks doit vous appartenir pour cela');
        }  

        $tricksImages = $tricksImageRepository->findBy(['trick' => $tricks->getId()]);

        foreach($tricksImages as $image){
            $tricks->addTricksImage($image);
        }

        $form = $this->createForm(TricksFormType::class, $tricks);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($tricks);
            $entityManager->flush();

            $this->addFlash('success', 'Tricks modifié!');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('tricks/form.html.twig', [
            'form' => $form->createView(),
            'tricks' => $tricks,
            'singleTrickPage' => true
        ]);
    }

    #[Route('/deleteTricks/{id}', name : "app_tricks_delete", methods:['GET','POST'])]
    public function delete(Tricks $tricks,Request $request,EntityManagerInterface $entityManager) : Response
    {
        if ($tricks->getUser() !== $this->getUser()) {
            $this->addFlash('error', 'Vous devez être propriétaire du tricks pour le supprimer');
            return $this->redirectToRoute('app_home');
        }

        $submittedToken = $request->request->get('token');

        if ($this->isCsrfTokenValid('delete-tricks', $submittedToken)) {

            foreach ($tricks->getComments() as $comment) {
                $entityManager->remove($comment);
            }
            $entityManager->remove($tricks);
            $entityManager->flush();
            $this->addFlash('success','Tricks supprimé');
            return $this->redirectToRoute('app_home');
        }

        $this->addFlash('error', 'Vous devez être propriétaire du serveur pour le supprimer');
        return $this->redirectToRoute('app_home');
    }
    
    #[Route('/ajaxTricks', name: 'app_tricks_json', methods:['GET'])]
    public function getTricksJson(TricksRepository $tricksRepository,Request $request) : JsonResponse
    {   
        $page = max(1, $request->query->getInt('page', 1));
        $paginator = $tricksRepository->getTricksPaginator($page);

        return new JsonResponse(['content' => $this->renderView('tricks/data.html.twig', [
            'tricks' => $paginator,
            'previous' => $page - 1,
            'next' => min(count($paginator), $page + 1),
            'tricks_per_page' => $tricksRepository::PAGINATOR_PER_PAGE
        ])]);
    }
}

templates/tricks/data.html.twig
{% for trick in tricks %}
	<div class="trick">
		{% if trick.featuredImageName %}
						<img src="{{ vich_uploader_asset(trick,'featuredImageFile') }}" alt="">
					{% else %}
						<img src="{{ asset('img/noimage.png') }}" alt="">
					{% endif %}
		<div>
			<a href="{{path('app_tricks_readOne', {'id' : trick.id})}}">{{trick.name|slice(0,20)}}</a>
			{% if app.user == trick.user %}
				<a href="{{path('app_edit_tricks', {'id' : trick.id})}}">
					<i class="fa-solid fa-pencil"></i>
				</a>
				<form class='deleteBtn' action="{{path('app_tricks_delete', {'id' : trick.id})}}" method='post' onsubmit='return (confirm("Voulez vous vraiment supprimer le serveur {{trick.name}} ?"))'>
					<input type="hidden" name="token" value="{{ csrf_token('delete-tricks') }}">
					<button type="submit">
						<i class="fa-solid fa-trash"></i>
					</button>
				</form>
			{% endif %}
		</div>
	</div>
{% endfor %}
<div class="pagination btn">
	{% if (next - 1) * tricks_per_page < tricks|length and tricks|length > 0 %}
		<a href="{{ path('app_tricks_json', { page: next }) }}">Charger plus</a>
	{% endif %}
</div>
<div class="chevron-up">
			<a href="#tricks"><i class="fa-solid fa-chevron-up"></i></a>
</div>

templates/tricks/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{% if form.name %}
		{{ form.name.vars.data }}{% else %}Création Tricks
	{% endif %}
{% endblock %}
{% block javascript %}
	{{ encore_entry_script_tags('tricksForm') }}
{% endblock %}

{% block body %}
	{% for flash_error in app.flashes('error') %}
		<div class="alert alert-danger" role="alert">{{ flash_error }}</div>
	{% endfor %}

	<div class="home-background background-single-trick">
		{{ form_start(form, {'attr': {'class': 'single-trick trick-form'}}) }}
		<div class='trick-action'>
			<i class="fa-solid fa-pencil"></i>
			<i class="fa-solid fa-trash"></i>
		</div>
		{% if tricks.featuredImageName %}
			<img class="featuredImage" src="{{ vich_uploader_asset(tricks,'featuredImageFile') }}" alt="">
		{% else %}
			<img src="{{ asset('img/noimage.png') }}" class='featuredImage' alt="">
		{% endif %}
		{{ form_widget(form.featuredImageFile, {attr:{ class : 'featuredImageInput'}})}}
		<div class="trickName">
			{{ form_widget(form.name) }}
			{{ form_errors(form.name) }}
		</div>
		<a class="mobile-media btn">Voir Médias</a>
		<div class="media-container ">
			<span title="Vidéos embed youtube seulement" class="videoInfo">
				<i class="fa-solid fa-info"></i>
			</span>
			<ul class="tricksVideos" data-index="{{ form.tricksVideos|length > 0 ? form.tricksVideos|last.vars.name + 1 : 0 }}" data-prototype="{{ form_widget(form.tricksVideos.vars.prototype)|e('html_attr') }}">
				{% for video in form.tricksVideos %}
					<li>
						{{form_widget(video.link)}}
					</li>
				{% endfor %}
			</ul>
			<button type="button" class="addTricksVideo" data-collection-holder-class="tricksVideos">
				<i class="fa-solid fa-plus"></i>
				<i class="fa-brands fa-youtube"></i>
			</button>
			<ul class="tricksImages" data-index="{{ form.tricksImages|length > 0 ? form.tricksImages|last.vars.name + 1 : 0 }}" data-prototype="{{ form_widget(form.tricksImages.vars.prototype)|e('html_attr') }}">
				{% for image in form.tricksImages %}
					<li>
						{{ form_row(image.file, {
                                label: false, attr: { class: 'uploadBtn' }
                            }) }}</li>
				{% endfor %}
			</ul>
			<button type="button" class="addTricksImage" data-collection-holder-class="tricksImages">
				<i class="fa-solid fa-plus"></i>
				<i class="fa-solid fa-image"></i>
			</button>
			<div class="mediaError">
				<ul class="videoErrors">
					{% for video in form.tricksVideos %}
						{% if form_errors(video.link) %}
							<li>
								Vidéo
								{{loop.index}}
								:
								{{form_errors(video.link)}}
							</li>
						{% endif %}

					{% endfor %}
				</ul>
				<ul class="videoErrors">
					{% for image in form.tricksImages %}
						{% if form_errors(image.file) %}
							<li>
								Image
								{{loop.index}}
								:
								{{form_errors(image.file)}}
							</li>
						{% endif %}
					{% endfor %}
				</ul>
			</div>
		</div>
		{{ form_widget(form.description) }}
		<div class="commentError">
			{{ form_errors(form.description) }}
		</div>
		<div class="trick-details">
			{{ form_widget(form.tricksGroup) }}
		</div>
		<div class='trick-form-action'>
			{% if tricks.id %}
				<button class="deleteBtn" onclick='return (confirm("Voulez vous vraiment supprimer le trick?"))'>Supprimer</button>
			{% endif %}

			<button type="submit">Enregistrer</button>
		</div>
		{{ form_end(form) }}
		{% if tricks.id  %}
			<form class='deleteForm' action="{{ path('app_tricks_delete', {'id': tricks.id}) }}" method='post'>
				<input type="hidden" name="token" value="{{ csrf_token('delete-tricks') }}">
				<button type="submit">
					<i class="fa-solid fa-trash"></i>
				</button>
			</form>
		{% endif %}

		{{ include("footer.html.twig", {singleTrickPage}) }}
	</div>
{% endblock %}

templates/tricks/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil
{% endblock %}

{% block javascript %}
	{{ encore_entry_script_tags('ajaxTricks') }}
{% endblock %}

{% block body %}

	{% for flash_error in app.flashes('unverified') %}
		<div class="alert alert-danger" role="alert">{{ flash_error }}</div>
	{% endfor %}
	{% for flash_error in app.flashes('verify_email_error') %}
		<div class="alert alert-danger" role="alert">{{ flash_error }}</div>
	{% endfor %}
	{% for flash_error in app.flashes('success') %}
		<div class="alert alert-danger" role="alert">{{ flash_error }}</div>
	{% endfor %}

	<div class="home-background">
		<h2>Le site pour partager votre passion et vos connaissances sur le sport de la glisse</h2>
		<a href="#tricks">
			<i class="fa-solid fa-circle-arrow-down"></i>
		</a>
	</div>
	{% if app.user and app.user.verified %}
		<a href={{path('app_add_tricks')}} class="addTrick">Ajouter un tricks</a>
	{% endif %}

	<div class="home-tricks">
		<div class="tricks-container" id="tricks">
			{% for trick in tricks %}
				<div class="trick">
					{% if trick.featuredImageName %}
						<img src="{{ vich_uploader_asset(trick,'featuredImageFile') }}" alt="">
					{% else %}
						<img src="{{ asset('img/noimage.png') }}" alt="">
					{% endif %}
					<div>
						<a href="{{path('app_tricks_readOne', {'id' : trick.id})}}">{{trick.name|slice(0,20)}}</a>
						{% if app.user == trick.user %}
							<a href="{{path('app_edit_tricks', {'id' : trick.id})}}">
								<i class="fa-solid fa-pencil"></i>
							</a>
							<form class='deleteBtn' action="{{path('app_tricks_delete', {'id' : trick.id})}}" method='post' onsubmit='return (confirm("Voulez vous vraiment supprimer le tricks {{trick.name}} ?"))'>
								<input type="hidden" name="token" value="{{ csrf_token('delete-tricks') }}">
								<button type="submit">
									<i class="fa-solid fa-trash"></i>
								</button>
							</form>
						{% endif %}
					</div>
				</div>
			{% endfor %}
			<div class="pagination btn">
				{% if (next - 1) * tricks_per_page < tricks|length and tricks|length > 0 %}
					<a href="{{ path('app_tricks_json', { page: next }) }}">Suivant</a>
				{% endif %}
			</div>
		</div>

	</div>
{% endblock %}

templates/tricks/readOne.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{trick.name}}
{% endblock %}
{% block javascript %}
	{{ encore_entry_script_tags('ajaxComment') }}
{% endblock %}

{% block body %}
	{% for flash_error in app.flashes('error') %}
		<div class="alert alert-danger" role="alert">{{ flash_error }}</div>
	{% endfor %}

	<div class="home-background background-single-trick">
		<div class="single-trick">
			<div class='trick-action'>
				{% if app.user == trick.user %}
					<a href="{{path('app_edit_tricks', {'id' : trick.id})}}">
						<i class="fa-solid fa-pencil"></i>
					</a>
					<form class='deleteBtn' action="{{path('app_tricks_delete', {'id' : trick.id})}}" method='post' onsubmit='return (confirm("Voulez vous vraiment supprimer le tricks {{trick.name}} ?"))'>
						<input type="hidden" name="token" value="{{ csrf_token('delete-tricks') }}">
						<button type="submit">
							<i class="fa-solid fa-trash"></i>
						</button>
					</form>
				{% endif %}
			</div>
			{% if trick.featuredImageName %}
				<img src="{{ vich_uploader_asset(trick,'featuredImageFile') }}" alt="">
				{% else %}
					<img src="{{ asset('img/noimage.png') }}" alt="">
				{% endif %}
			<h1>{{trick.name}}</h1>
			<a href="" class="mobile-media btn">Voir Médias</a>
			<div class="media-container">
				{% for image in trick.tricksImages %}
					<img src='{{ vich_uploader_asset(image) }}'>
				{% endfor %}
				{% for video in trick.tricksVideos %}
					<iframe src="{{video.link}}" frameborder="0"></iframe>
				{% endfor %}
			</div>
			<p>{{trick.description}}</p>
			<div class="trick-details">
				<p>{{trick.tricksGroup.name}}</p>
				<p>Crée par :
					{{trick.user.username}}</p>
			</div>
			{% if app.user %}
				{{ include('comment/_form.html.twig', {'button_label': 'Poster'}) }}
			{% endif %}
			<div class="comments-container">
				{% for comment in comments %}
					<div class="comment" comment-id="{{comment.id}}">
						<img src='../img/avatar/{{ comment.user.picture }}.png'>
						<div class="comment-details">
							<div class="commentContent">
							{% if app.user == comment.user %}
								<div class="comment-action">
									<a class="editBtn">
										<i class="fa-solid fa-pencil"></i>
									</a>
									{% include "comment/_delete_form.html.twig" %}
								</div>
							{% endif %}
							<p>{{comment.content}}</p>
							</div>
							<p class="commentError"></p>
						</div>
					</div>
				{% endfor %}
				<div class="pagination">
					{% if (next - 1) * comment_per_page < comments|length and comments|length > 0 %}
						<a href="{{ path('app_comments_json', { id: trick.id, page: next }) }}">Plus de commentaire</a>
					{% endif %}
				</div>
			</div>
		</div>
		{{ include("footer.html.twig", {singleTrickPage}) }}
	</div>
{% endblock %}